spring:
  datasource:
    druid:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:13306/mysql57?useUnicode=true&characterEncoding=utf-8&useSSL=false
      password: abc123
      username: root
mybatis-plus:
  global-config:
    db-config:
      table-prefix: "tbl_"
      id-type: auto
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
server:
  port: 80