spring:
  profiles:
    active: @profileActive@
    group:
      "dev": dev,devDB
      "test": test
  mail:
    host: smtp.qq.com
    username: XXX@qq.com
    password: XXX

a:
  name: ${random.value}
  age : ${random.int}
