spring:
  profiles:
    active: @profileActive@
    group:
      "dev": dev,devDB
      "test": test
  mail:
#    host: smtp.qq.com
    host: smtp.126.com
    username: xxx@xxx.com
    password: xxx

a:
  name: ${random.value}
  age : ${random.int}
